### ISSUE TITLE
Support for python 3.7

### ISSUE THREAD

**Issue by newwarez** [kimmobrunfeldt/nap#14]
Hi, 
I would like to ask if you are willing to provide support for the recent python versions since it seems that it is currently not compatible with them.

**Comment by ilkka** [comment]
As far as tests are concerned it seems that only some URL joining tests fail and these seem to be related to #12 , funnily enough. Are there other known incompatibilities with Python 3.7?

**Comment by kimmobrunfeldt** [comment]
This should be fixed after merging #15.
